[package]
name = "rmatrix"
version = "0.2.0"
authors = ["Maciej Augustyniak"]
edition = "2024"
description = "Matrix like animation running in terminal"
repository = "https://github.com/magmast/rmatrix"
keywords = ["matrix"]
license = "MIT"

[badges]
codecov = { repository = "magmast/rmatrix" }
maintenance = { status = "passively-maintained" }

[dependencies]
anyhow = "1.0.97"
bon = "3.5.1"
clap = { version = "4.5.35", features = ["derive"] }
crossterm = { version = "0.28.1", features = ["serde"] }
directories = "6.0.0"
rand = "0.9.0"
serde_plain = "1.0.2"
time = { version = "0.3.44", features = ["local-offset"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }

[dev-dependencies]
itertools = "0.14.0"
