[package]
name = "rmatrix"
version = "0.1.1"
authors = ["Maciej Augustyniak"]
edition = "2024"
description = "Matrix like animation running in terminal"
repository = "https://github.com/magmast/rmatrix"
keywords = ["ncurses", "matrix"]
license = "MIT"

[badges]
codecov = { repository = "magmast/rmatrix" }
maintenance = { status = "passively-maintained" }

[dependencies]
ncurses = "5.99"
rand = "0.6"